---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-{{ .Release.Name }}
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      server_name _;

      location / {
        root   /app/frontend;
        index  index.html;
      }

      location /api {
          proxy_pass http://backend:{{ .Values.global.backendPort | int }};
      }
    }