apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "64Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" | quote }}
              memory: {{ .Values.resources.limits.memory | default "128Mi" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.port | default 80 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: "nginx-conf-{{ .Release.Name }}"
      imagePullSecrets:
        - name: docker-config-secret-helm