apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          name: "{{ .Values.name }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_datasource
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-helm
                  key: mongodb_datasource
            - name: BACKEND_PORT
              value: "{{ .Values.global.backendPort }}"
            - name: SPRING_FLYWAY_BASELINE
              value: "{{ .Values.global.springFlywayBaseline }}"
          ports:
            - name: backend
              containerPort: {{ .Values.global.backendPort | int }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.global.backendPort | int }}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.global.backendPort | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      imagePullSecrets:
        - name: docker-config-secret-helm