# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtZXh0LTAxOS0wMSIsInBhc3N3b3JkIjoiSkMyNjVrZDgiLCJhdXRoIjoiYzNSa0xXVjRkQzB3TVRrdE1ERTZTa015TmpWclpEZz0ifX19
type: kubernetes.io/dockerconfigjson