global:
  springDatasourceUrl: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DBNAME}
  backendPort: 8080
  springFlywayBaseline: true
  appName: sausage-store
  environment: test
  imageRegistry: gitlab.praktikum-services.ru:5050/anton-alekseyev/sausage-store