---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-helm
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
stringData:
  postgres_datasource: {{ required "set .Values.secrets.postgres_datasource" (index .Values.secrets "postgres_datasource") | quote }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-helm
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
stringData:
  mongodb_datasource: {{ required "set .Values.secrets.mongodb_datasource" (index .Values.secrets "mongodb_datasource") | quote }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-helm
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "set .Values.secrets.dockerConfigJson" .Values.secrets.dockerConfigJson | quote }}
  .dockerconfigjson: {{ required "set .Values.secrets.dockerConfigJson"  (index .Values.secrets "dockerConfigJson") | quote }}