---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-helm
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
stringData:
  postgres_datasource: {{ .Values.secrets.postgres_datasource | default "" | b64enc }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-helm
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson  | default "" | b64enc }}