---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  containers:
    - image: gitlab.praktikum-services.ru:5050/std-ext-019-01/sausage-store/sausage-frontend:latest
      name: backend-report
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 2
        failureThreshold: 6
  imagePullSecrets:
    - name: docker-config-secret
