---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: sausage-store
    app.kubernetes.io/version: "${VERSION}"
spec:
  revisionHistoryLimit: 12
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: availability-zone
                    operator: In
                    values:
                      - zone1 
      imagePullSecrets:
        - name: docker-config-secret
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-ext-019-01/sausage-store/sausage-backend-report:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3